### ISSUE TITLE
Urdu translation no longer being maintained

### ISSUE THREAD

**Issue by Touseef-ahmad** [reactjs/ur.reactjs.org#128]
@jabranr are you no longer maintaining the repo? can i be a maintainer in the repo.

**Comment by jabranr** [comment]
@Touseef-ahmad I am but I believe the overall progress/contribution on it has been quite slow.

**Comment by hallucinogenizer** [comment]
@jabranr can you point me to a resource to let me know wherefrom I can start contributing exactly?

**Comment by jabranr** [comment]
@hallucinogenizer You can see a list of topics at https://github.com/reactjs/ur.reactjs.org/issues/59

Beware that this list needs a review.

**Comment by Touseef-ahmad** [comment]
@jabranr I am leading a frontend React JS developer team, and all my team members are interested in contributing to this project. If you can give me maintainer access that would be great.

**Comment by jabranr** [comment]
@Touseef-ahmad fair enough. I have now added you as a maintainer for this repo. Godspeed!
