### ISSUE TITLE
Linux Urdu Translation? Linux Manto

### ISSUE THREAD

**Issue by waqarrashid33** [reactjs/ur.reactjs.org#18]
Anyone know anyone who would be interested, here is the link:
https://github.com/pakistan-dev-for-covid-19/Linux-Manto

# Linux-Manto
Linux Transaltion into Urdu

# Based on:
	-> GNU
	-> Linux
	-> Ubuntu/Mint

Saadat Hasan Manto
https://en.wikipedia.org/wiki/Saadat_Hasan_Manto
![Saadat Hasan Manto](/Saadat_Hasan_Manto_photograph.jpg)

Name: Linux Manto (Manto Written in Urdu)
Reason: Manto sounds simliar to ubuntu or ubuntu based distros
 <image> Logo <image>

Code Name: Pyasa Kawa (Thirsty Crow) Based on 20.04 / Linux Manto 20.04
I am starting working on this project out of neccisity so hence the name Thristy Crow

Logo Name: Linux <urdu>Manto</urdu>

Code names: Urdu writers, poets, artists (First version is Manto)

**Comment by jabranr** [comment]
I don't think this is anyway relevant to this React translation.

**Comment by waqarrashid33** [comment]
Ok. Fair enough. I was looking for Pakistani open source developers.
