### ISSUE TITLE
Translate Courses page

### ISSUE THREAD

**Issue by mhkasif** [reactjs/ur.reactjs.org#21]
Hello members,

I would like to play my part in translating **content/community** files.
out of which I've translated **courses.md** file,
and looking forward to translate more.

It would be great if you give me a chance.

Thanks

**Comment by jabranr** [comment]
@mhkasif  Thank you.

I have updated the title of this issue to reflect relevant work needed to be done as part of this.

Here is the reference link to the page that you are working on:

https://deploy-preview-20--ur-reactjs.netlify.app/community/courses.html

**Comment by mhkasif** [comment]
@jabranr Thanks for responding
I'll look at the issues and try to fix it soon.
